PYTHON ?= python3
PIP ?= pip

.PHONY: help install lint format typecheck test coverage audit run compose-up compose-down qdrant-init ingest version sbom scan e2e smoke

help:
	@echo "Targets: install, lint, format, typecheck, test, coverage, audit, run, compose-up, compose-down"

install:
	$(PIP) install --upgrade pip
	$(PIP) install -e .[dev]

lint:
	flake8 src tests
	pylint src

format:
	black src tests
	isort src tests

typecheck:
	mypy src

test:
	pytest -q --maxfail=1

coverage:
	pytest --cov=src --cov-report=term-missing --cov-report=xml --cov-fail-under=80

audit:
	pip-audit -r requirements.txt || true

run:
	uvicorn cortex_ka.api.main:app --host 0.0.0.0 --port 8088 --reload

compose-up:
	docker compose -f docker/compose.yml up -d --build

compose-down:
	docker compose -f docker/compose.yml down

qdrant-init:
	$(PYTHON) -m cortex_ka.scripts.init_qdrant

ingest:
	$(PYTHON) -m cortex_ka.scripts.ingest_docs

# Developer smoke test against a running API at SMOKE_BASE_URL (default http://localhost:8088)
smoke:
	$(PYTHON) -m scripts.try_it

# Embed Git metadata and UTC build time into src/cortex_ka/build_info.py
version:
	@GIT_SHA=$$(git rev-parse --short=12 HEAD 2>/dev/null || echo unknown); \
	BUILD_TIME=$$(date -u +"%Y-%m-%dT%H:%M:%SZ"); \
	APP_VERSION=$$(python -c 'import tomllib,sys;print(tomllib.load(open("pyproject.toml","rb"))["project"]["version"])' 2>/dev/null || echo 0.1.0); \
	echo "Updating build_info.py with $$GIT_SHA @ $$BUILD_TIME (version $$APP_VERSION)"; \
	printf '"""Build metadata placeholders.\n\nThis file is generated by `make version`.\n"""\n\nAPP_VERSION = "%s"\nGIT_SHA = "%s"\nBUILD_TIME_UTC = "%s"\n' "$$APP_VERSION" "$$GIT_SHA" "$$BUILD_TIME" > src/cortex_ka/build_info.py

# Generate SBOM with Syft (CycloneDX JSON)
sbom:
	@command -v syft >/dev/null 2>&1 || { echo "Syft not installed. See https://github.com/anchore/syft#installation"; exit 1; }
	syft packages . -o cyclonedx-json=sbom.json
	@echo "SBOM written to sbom.json"

# Scan built image with Trivy (fails on HIGH/CRITICAL)
scan:
	@command -v trivy >/dev/null 2>&1 || { echo "Trivy not installed. See https://aquasecurity.github.io/trivy/"; exit 1; }
	docker build -f docker/Dockerfile.api -t cortex-ka:local .
	trivy image --severity HIGH,CRITICAL --exit-code 1 --ignore-unfixed cortex-ka:local

# Run end-to-end tests (marked with @pytest.mark.e2e)
e2e:
	pytest -q -m e2e
